eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: eurekaClient
spring:
  application:
    name: client
server:
  port: 8080
evn: test
