# eureka:
#   client:
#     service-url:
# #      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: eurekaClient
spring:
  application:
    name: client
  rabbitmq:
    host: 47.92.96.175
    port: 5672
    username: user
    password: 2wxSWING
server:
  port: 8080
evn: dev111
